version: '3.8'
services:
  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: studentdb
      POSTGRES_USER: student
      POSTGRES_PASSWORD: student
    volumes:
      - postgres_volume:/var/lib/postgresql/data/
    network_mode: host
  cassandra:
    image: cassandra
    ports:
      - 9042:9042
    volumes:
      - cassandra_volume:/var/lib/cassandra    
  jupyter:
    image: jupyter/all-spark-notebook
    environment:
      JUPYTER_ENABLE_LAB: 1
    volumes:
      - ./:/home/jovyan/work
    ports:
      - "8888:8888"
    #network_mode: host


volumes:
  postgres_volume:
  cassandra_volume:
