version: '3.8'
services:
  jupyter:
    image: jupyter/all-spark-notebook
    environment:
      JUPYTER_ENABLE_LAB: 1
    volumes:
      - ./:/home/jovyan/work
    ports:
      - "8888:8888"
    network_mode: host
